### ISSUE TITLE
Update conda-forge feedstock

### ISSUE THREAD

**Issue by owen-synergy** [yehoshuadimarsky/bcpandas#11]
Hi @yehoshuadimarsky - were you planning to update the [conda-forge feedstock auto PR](https://github.com/conda-forge/bcpandas-feedstock/pull/17)?

If you wanted a hand you can add my personal GitHub account:

owenlamont

as a recipe-maintainer in the meta.yaml

I'd be happy to help keep it in sync with the PyPi package (I'm keen to be able to conda install it myself).

**Comment by yehoshuadimarsky** [comment]
Yeah sorry I messed up with the version, accidentally uploaded 1.0.0 to PyPi, then "yanked" it but conda-forge doesn't recognize that apparently, so I guess will need to manually update the `meta.yaml` file instead of relying on their automated tools. I'll do it now. 

But thanks for the offer to help with it, I'll add you as a maintainer.

**Comment by owen-synergy** [comment]
> Yeah sorry I messed up with the version, accidentally uploaded 1.0.0 to PyPi, then "yanked" it but conda-forge doesn't recognize that apparently, so I guess will need to manually update the `meta.yaml` file instead of relying on their automated tools. I'll do it now.
> 
> But thanks for the offer to help with it, I'll add you as a maintainer.

I got the invite, cheers! Happy to help. I'm trying to learn the ropes with conda-forge too - I think from the text on the PR there is a label or message you can send to their bot to make it close and create a new PR. I had hoped that would fix the problem but not sure.
