### ISSUE TITLE
Cant import into database

### ISSUE THREAD

**Issue by AnnihilateID01** [yehoshuadimarsky/bcpandas#30]
Hi,

I try to use bcpandas to load a csv into  a database (mssql). I use Trusted Connection when I connect to the database. Unfortunately, i get this error when I try to bulk my data into my database :

Error = [Microsoft][ODBC Driver 17 for SQL Server]Incorrect host-column number found in BCP format-file

Do you know what kind of problem can trigger this ?

Thanks you,
David

**Comment by LevonW-IIS** [comment]
I'm getting the same issue (Incorrect host-column number found in BCP format-file), and have yet to find a solution

**Comment by Moraziel** [comment]
had the same issue, removed spaces from column headers and it worked.
ex: `df.columns = df.columns.str.replace(' ','_')`
cf https://www.sqlservercentral.com/forums/topic/problem-with-bcp-and-format-file 
(it's more of an issue with bcp rather than bcpandas, but bcpandas could check for this before trying to execute and display a warning)

**Comment by dherskowitz** [comment]
I had the same issue and was able to resolve it with @Moraziel solution.

**Comment by sfirke** [comment]
That fix from @Moraziel would be great in an FAQ.  Also working around cases when bcpandas fails due to all delimiters being used -- I replace one of them in all columns.  If there was an appropriate place to start such an FAQ, I'd send a PR with those two tips.

**Comment by yehoshuadimarsky** [comment]
Thanks @sfirke - you can submit a PR that starts an FAQ!

**Comment by sfirke** [comment]
I think this can be closed @yehoshuadimarsky - the only actionable example is that of having spaces in column names, and that was just fixed in #149.  I just tested and bcpandas now writes a dataframe with columns that have spaces in the names.

**Comment by yehoshuadimarsky** [comment]
Awesome happy to hear!

**Comment by sfirke** [comment]
Some fun closure: I bumped my ETL environment to bcpandas 2.6.0 today.  This update, which meant one of my dataframes with spaces could write with BCP instead of Pandas, cut one of my ETL tasks from a 9 minute runtime to a 1 minute runtime 😁 

Airflow job runtimes chart:
![image](https://github.com/yehoshuadimarsky/bcpandas/assets/7569808/d9dea9a8-d48f-433e-adaf-e5b9cef90add)

**Comment by yehoshuadimarsky** [comment]
So great to hear! Awesome to hear success stories where this project makes a big difference
